/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach,
	init,
	insert_experimental,
	make_renderer,
	noop,
	safe_not_equal
} from "svelte/internal";

const render = make_renderer(`<div class="divider"></div>`);

// (7:0) {#if (item.divider && item.divider.includes(1))}
function create_if_block(ctx) {
	let div;

	return {
		c() {
			div = render().firstChild;
		},
		m(target, anchor) {
			insert_experimental(target, div, anchor);
		},
		d(detaching) {
			if (detaching) detach(div);
		}
	};
}

const render_1 = make_renderer(`<!>`);

function create_fragment(ctx) {
	let show_if = /*item*/ ctx[0].divider && /*item*/ ctx[0].divider.includes(1);
	let if_block_anchor;
	let if_block = show_if && create_if_block(ctx);

	return {
		c() {
			if_block_anchor = render_1().firstChild;
			if (if_block) if_block.c();
		},
		m(target, anchor) {
			if (if_block) if_block.m(target, anchor);
			insert_experimental(target, if_block_anchor, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(if_block_anchor);
			if (if_block) if_block.d(detaching);
		}
	};
}

function instance($$self) {
	let item = { divider: [1] };
	return [item];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Component;