/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach,
	first_child,
	init,
	insert_experimental,
	make_renderer,
	noop,
	replace_text,
	safe_not_equal,
	set_data
} from "svelte/internal";

import { onMount } from 'svelte';
const render = make_renderer(`<p><!></p>`);

function create_fragment(ctx) {
	let p;
	let t;

	return {
		c() {
			p = first_child(render());
			t = replace_text(first_child(p), /*y*/ ctx[0]);
		},
		m(target, anchor) {
			insert_experimental(target, p, anchor);
		},
		p(ctx, [dirty]) {
			if (dirty & /*y*/ 1) set_data(t, /*y*/ ctx[0]);
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(p);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let x;
	let y;
	let a = 1, b = 2, c = 3;

	onMount(() => {
		const interval = setInterval(
			() => {
				$$invalidate(1, b += 1);
				c += 1;
				console.log(b, c);
			},
			1000
		);

		return () => clearInterval(interval);
	});

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*b*/ 2) {
			$: $$invalidate(0, y = b * 2);
		}
	};

	$: x = a * 2;
	return [y, b];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Component;