/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	component_subscribe,
	detach,
	init,
	insert_experimental,
	make_renderer,
	noop,
	safe_not_equal,
	set_data
} from "svelte/internal";

import { writable } from 'svelte/store';
const render = make_renderer(`<h1> </h1>`);

function create_fragment(ctx) {
	let h1;
	let t;

	return {
		c() {
			h1 = render().firstChild;
			t = h1.firstChild;
			t.data = /*$foo*/ ctx[0];
		},
		m(target, anchor) {
			insert_experimental(target, h1, anchor);
		},
		p(ctx, [dirty]) {
			if (dirty & /*$foo*/ 1) set_data(t, /*$foo*/ ctx[0]);
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(h1);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let $foo;
	const foo = writable(0);
	component_subscribe($$self, foo, value => $$invalidate(0, $foo = value));
	return [$foo, foo];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Component;