/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach_all,
	init,
	insert_all,
	listen,
	make_renderer,
	noop,
	safe_not_equal,
	set_data,
	set_input_value,
	traverse
} from "svelte/internal";

const render = make_renderer(`<p> </p> <input>`);
const node_path = () => [,0,2,1];

function create_fragment(ctx) {
	let render_nodes = [];
	let mounted;
	let dispose;

	return {
		c() {
			traverse(render(), render_nodes, node_path());
			render_nodes[1].data = /*foo*/ ctx[0];
		},
		m(target, anchor) {
			insert_all(target, render_nodes, [0,2,3], anchor);
			set_input_value(render_nodes[3], /*foo*/ ctx[0]);

			if (!mounted) {
				dispose = listen(render_nodes[3], "input", /*input_input_handler*/ ctx[1]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (dirty & /*foo*/ 1) set_data(render_nodes[1], /*foo*/ ctx[0]);

			if (dirty & /*foo*/ 1 && render_nodes[3].value !== /*foo*/ ctx[0]) {
				set_input_value(render_nodes[3], /*foo*/ ctx[0]);
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			detach_all(detaching, render_nodes, [0,2,3]);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let foo = "bar";

	function input_input_handler() {
		foo = this.value;
		$$invalidate(0, foo);
	}

	return [foo, input_input_handler];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Component;