/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	comment,
	detach,
	init,
	insert,
	make_renderer,
	noop,
	safe_not_equal,
	traverse
} from "svelte/internal";

const render_1 = make_renderer(`<p>not foo!</p>`);

// (7:0) {:else}
function create_else_block(ctx) {
	let render_nodes = [];

	return {
		c() {
			traverse(render_1(), render_nodes);
		},
		m(target, anchor) {
			insert(target, render_nodes[0], anchor); /* p */
		},
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* p */
		}
	};
}

const render = make_renderer(`<p>foo!</p>`);

// (5:0) {#if foo}
function create_if_block(ctx) {
	let render_nodes = [];

	return {
		c() {
			traverse(render(), render_nodes);
		},
		m(target, anchor) {
			insert(target, render_nodes[0], anchor); /* p */
		},
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* p */
		}
	};
}

function create_fragment(ctx) {
	let if_block_anchor = comment();

	function select_block_type(ctx, dirty) {
		if (/*foo*/ ctx[0]) return create_if_block;
		return create_else_block;
	}

	let current_block_type = select_block_type(ctx, -1);
	let if_block = current_block_type(ctx);

	return {
		c() {
			if_block.c();
		},
		m(target, anchor) {
			insert(target, if_block_anchor, anchor);
			if_block.m(target, if_block_anchor);
		},
		p(ctx, [dirty]) {
			if (current_block_type !== (current_block_type = select_block_type(ctx, dirty))) {
				if_block.d(1);
				if_block = current_block_type(ctx);

				if (if_block) {
					if_block.c();
					if_block.m(if_block_anchor.parentNode, if_block_anchor);
				}
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(if_block_anchor);
			if_block.d(detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { foo } = $$props;

	$$self.$$set = $$props => {
		if ('foo' in $$props) $$invalidate(0, foo = $$props.foo);
	};

	return [foo];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { foo: 0 });
	}
}

export default Component;