/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	attr,
	detach_all,
	init,
	insert_all_hydration,
	make_renderer,
	noop,
	safe_not_equal,
	src_url_equal,
	traverse,
	traverse_claim
} from "svelte/internal";

const render = make_renderer(`<img alt="potato"> <img alt="potato">`);
const node_path = () => [,1,1];

function create_fragment(ctx) {
	let render_nodes = [];
	let img0_src_value;
	let img1_src_value;

	return {
		c() {
			traverse(render(), render_nodes, node_path());
			this.h();
		},
		l(nodes) {
			this.c();
			traverse_claim(nodes, render_nodes, node_path());
			this.h();
		},
		h() {
			if (!src_url_equal(render_nodes[0].src, img0_src_value = /*url*/ ctx[0])) attr(render_nodes[0], "src", img0_src_value);
			if (!src_url_equal(render_nodes[2].src, img1_src_value = "" + (/*slug*/ ctx[1] + ".jpg"))) attr(render_nodes[2], "src", img1_src_value);
		},
		m(target, anchor) {
			insert_all_hydration(target, render_nodes, [0,1,2], anchor);
		},
		p(ctx, [dirty]) {
			if (dirty & /*url*/ 1 && !src_url_equal(render_nodes[0].src, img0_src_value = /*url*/ ctx[0])) {
				attr(render_nodes[0], "src", img0_src_value);
			}

			if (dirty & /*slug*/ 2 && !src_url_equal(render_nodes[2].src, img1_src_value = "" + (/*slug*/ ctx[1] + ".jpg"))) {
				attr(render_nodes[2], "src", img1_src_value);
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			detach_all(detaching, render_nodes, [0,1,2]);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { url } = $$props;
	let { slug } = $$props;

	$$self.$$set = $$props => {
		if ('url' in $$props) $$invalidate(0, url = $$props.url);
		if ('slug' in $$props) $$invalidate(1, slug = $$props.slug);
	};

	return [url, slug];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { url: 0, slug: 1 });
	}
}

export default Component;