/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	attr,
	detach,
	init,
	insert_hydration,
	make_renderer,
	noop,
	safe_not_equal,
	src_url_equal,
	traverse,
	traverse_claim
} from "svelte/internal";

const render = make_renderer(`<img alt="potato"> <img alt="potato">`);
const node_path = () => [,-1,-1];

function create_fragment(ctx) {
	let render_nodes = [];
	let img0_src_value;
	let img1_src_value;

	return {
		c() {
			traverse(render(), render_nodes, node_path());
			this.h();
		},
		l(nodes) {
			this.c();
			if (!nodes.length) return;
			const claim_func_var = new Map();
			traverse_claim(nodes, render_nodes, node_path(), claim_func_var, 0);
			this.h();
		},
		h() {
			if (!src_url_equal(render_nodes[0].src, img0_src_value = /*url*/ ctx[0])) attr(render_nodes[0], "src", img0_src_value);
			if (!src_url_equal(render_nodes[2].src, img1_src_value = "" + (/*slug*/ ctx[1] + ".jpg"))) attr(render_nodes[2], "src", img1_src_value);
		},
		m(target, anchor) {
			insert_hydration(target, render_nodes[0], anchor); /* img0 */
			insert_hydration(target, render_nodes[1], anchor); /* t */
			insert_hydration(target, render_nodes[2], anchor); /* img1 */
		},
		p(ctx, [dirty]) {
			if (dirty & /*url*/ 1 && !src_url_equal(render_nodes[0].src, img0_src_value = /*url*/ ctx[0])) {
				attr(render_nodes[0], "src", img0_src_value);
			}

			if (dirty & /*slug*/ 2 && !src_url_equal(render_nodes[2].src, img1_src_value = "" + (/*slug*/ ctx[1] + ".jpg"))) {
				attr(render_nodes[2], "src", img1_src_value);
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* img0 */
			if (detaching) detach(render_nodes[1]); /* t */
			if (detaching) detach(render_nodes[2]); /* img1 */
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { url } = $$props;
	let { slug } = $$props;

	$$self.$$set = $$props => {
		if ('url' in $$props) $$invalidate(0, url = $$props.url);
		if ('slug' in $$props) $$invalidate(1, slug = $$props.slug);
	};

	return [url, slug];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { url: 0, slug: 1 });
	}
}

export default Component;