/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach,
	first_child,
	init,
	insert,
	make_renderer,
	noop,
	safe_not_equal
} from "svelte/internal";

const render = make_renderer(`<b> </b>`);

function create_fragment(ctx) {
	let b;
	let t_value = get_answer() + "";
	let t;

	return {
		c() {
			b = first_child(render());
			t = first_child(b);
			t.data = t_value;
		},
		m(target, anchor) {
			insert(target, b, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(b);
		}
	};
}

const ANSWER = 42;

function get_answer() {
	return ANSWER;
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;