/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach,
	init,
	insert,
	make_renderer,
	noop,
	safe_not_equal,
	traverse
} from "svelte/internal";

const render = make_renderer(`<b> </b>`);
const node_path = () => [0,0];

function create_fragment(ctx) {
	let render_nodes = [];
	let t_value = get_answer() + "";

	return {
		c() {
			traverse(render(), render_nodes, node_path());
			render_nodes[1].data = t_value;
		},
		m(target, anchor) {
			insert(target, render_nodes[0], anchor); /* b */
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* b */
		}
	};
}

const ANSWER = 42;

function get_answer() {
	return ANSWER;
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;