/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach,
	first_child,
	first_element_child,
	init,
	insert_experimental,
	listen,
	make_renderer,
	next_element_sibling,
	noop,
	run_all,
	safe_not_equal,
	set_input_value
} from "svelte/internal";

const render = make_renderer(`<form><input type="text" required> <button>Store</button></form>`);

function create_fragment(ctx) {
	let form;
	let input;
	let button;
	let mounted;
	let dispose;

	return {
		c() {
			form = first_child(render());
			input = first_element_child(form);
			button = next_element_sibling(input);
			input.required = true;
		},
		m(target, anchor) {
			insert_experimental(target, form, anchor);
			set_input_value(input, /*test*/ ctx[0]);

			if (!mounted) {
				dispose = [
					listen(input, "input", /*input_input_handler*/ ctx[2]),
					listen(form, "submit", /*handleSubmit*/ ctx[1])
				];

				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (dirty & /*test*/ 1 && input.value !== /*test*/ ctx[0]) {
				set_input_value(input, /*test*/ ctx[0]);
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(form);
			mounted = false;
			run_all(dispose);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let test = undefined;

	function handleSubmit(event) {
		event.preventDefault();
		console.log('value', test);
	}

	function input_input_handler() {
		test = this.value;
		$$invalidate(0, test);
	}

	return [test, handleSubmit, input_input_handler];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Component;