/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach,
	init,
	insert,
	make_renderer,
	noop,
	replace_text,
	safe_not_equal,
	traverse
} from "svelte/internal";

const render = make_renderer(`<h1>Hello <!>!</h1>`);
const node_path = () => [,,-1,1];

function create_fragment(ctx) {
	let render_nodes = [];

	return {
		c() {
			traverse(render(), render_nodes, node_path());
			render_nodes[2] = replace_text(render_nodes[2], name);
		},
		m(target, anchor) {
			insert(target, render_nodes[0], anchor); /* h1 */
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* h1 */
		}
	};
}

let name = 'world';

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;