/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	create_component,
	destroy_component,
	detach,
	init,
	insert,
	make_renderer,
	mount_component,
	noop,
	safe_not_equal,
	transition_in,
	transition_out,
	traverse
} from "svelte/internal";

import LazyLoad from './LazyLoad.svelte';
const render = make_renderer(`<!>`);

function create_fragment(ctx) {
	let render_nodes = [];
	let lazyload;
	let current;
	lazyload = new LazyLoad({ props: { load: func } });

	return {
		c() {
			traverse(render(), render_nodes);
			create_component(lazyload.$$.fragment);
		},
		m(target, anchor) {
			insert(target, render_nodes[0], anchor); /* lazyload */
			mount_component(lazyload, target, render_nodes[0]);
			current = true;
		},
		p: noop,
		i(local) {
			if (current) return;
			transition_in(lazyload.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(lazyload.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* lazyload */
			destroy_component(lazyload, detaching);
		}
	};
}

const func = () => import('./Foo.svelte');

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;