/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	append_experimental,
	detach,
	first_child,
	init,
	make_renderer,
	next_element_sibling,
	noop,
	safe_not_equal
} from "svelte/internal";

const render = make_renderer(`<meta name="twitter:creator" content="@sveltejs"><meta name="twitter:title" content="Svelte">`);

function create_fragment(ctx) {
	let meta0;
	let meta1;

	return {
		c() {
			meta0 = first_child(render());
			meta1 = next_element_sibling(meta0);
		},
		m(target, anchor) {
			append_experimental(document.head, meta0);
			append_experimental(document.head, meta1);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			detach(meta0);
			detach(meta1);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;