/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach,
	first_child,
	first_element_child,
	init,
	insert_experimental,
	make_renderer,
	next_element_sibling,
	noop,
	safe_not_equal,
	select_option
} from "svelte/internal";

const render = make_renderer(`<select><option value="1">1</option><option value="2">2</option></select>`);

function create_fragment(ctx) {
	let select;
	let option0;
	let option1;

	return {
		c() {
			select = first_child(render());
			option0 = first_element_child(select);
			option1 = next_element_sibling(option0);
			option0.__value = "1";
			option0.value = option0.__value;
			option1.__value = "2";
			option1.value = option1.__value;
		},
		m(target, anchor) {
			insert_experimental(target, select, anchor);
			select_option(select, /*current*/ ctx[0]);
		},
		p(ctx, [dirty]) {
			if (dirty & /*current*/ 1) {
				select_option(select, /*current*/ ctx[0]);
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(select);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { current } = $$props;

	$$self.$$set = $$props => {
		if ('current' in $$props) $$invalidate(0, current = $$props.current);
	};

	return [current];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { current: 0 });
	}
}

export default Component;