/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	attr,
	claim_element_experimental,
	claim_text_experimental,
	detach,
	init,
	insert_experimental_hydration,
	make_renderer,
	noop,
	safe_not_equal,
	src_url_equal
} from "svelte/internal";

const render = make_renderer(`<img src="donuts.jpg" alt="donuts"> <div></div>`);

function create_fragment(ctx) {
	let img;
	let img_src_value;
	let t;
	let div;

	return {
		c() {
			img = render().firstChild;
			t = img.nextSibling;
			div = t.nextElementSibling;
			this.h();
		},
		l(nodes) {
			this.c();
			if (!nodes.length) return;
			img = claim_element_experimental(img, nodes);
			t = claim_text_experimental(t, nodes);
			div = claim_element_experimental(div, nodes);
			this.h();
		},
		h() {
			if (!src_url_equal(img.src, img_src_value = "donuts.jpg")) attr(img, "src", img_src_value);
		},
		m(target, anchor) {
			insert_experimental_hydration(target, img, anchor);
			insert_experimental_hydration(target, t, anchor);
			insert_experimental_hydration(target, div, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(img);
			if (detaching) detach(t);
			if (detaching) detach(div);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;