/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	attr,
	detach,
	init,
	insert_hydration,
	make_renderer,
	noop,
	safe_not_equal,
	src_url_equal,
	traverse,
	traverse_claim
} from "svelte/internal";

const render = make_renderer(`<img src="donuts.jpg" alt="donuts"> <div></div>`);
const node_path = () => [,-1,-1];

function create_fragment(ctx) {
	let render_nodes = [];
	let img_src_value;

	return {
		c() {
			traverse(render(), render_nodes, node_path());
			this.h();
		},
		l(nodes) {
			this.c();
			if (!nodes.length) return;
			const claim_func_var = new Map();
			traverse_claim(nodes, render_nodes, node_path(), claim_func_var, 0);
			this.h();
		},
		h() {
			if (!src_url_equal(render_nodes[0].src, img_src_value = "donuts.jpg")) attr(render_nodes[0], "src", img_src_value);
		},
		m(target, anchor) {
			insert_hydration(target, render_nodes[0], anchor); /* img */
			insert_hydration(target, render_nodes[1], anchor); /* t */
			insert_hydration(target, render_nodes[2], anchor); /* div */
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* img */
			if (detaching) detach(render_nodes[1]); /* t */
			if (detaching) detach(render_nodes[2]); /* div */
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;