/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	attr,
	detach,
	init,
	insert_experimental,
	make_renderer,
	noop,
	safe_not_equal,
	src_url_equal
} from "svelte/internal";

const render = make_renderer(`<div><img alt="Star" width="100" height="100" src="http://mdn.mozillademos.org/files/12676/star.svg"></div>`);

function create_fragment(ctx) {
	let div;
	let img;
	let img_src_value;

	return {
		c() {
			div = render().firstChild;
			img = div.firstElementChild;
			if (!src_url_equal(img.src, img_src_value = "http://mdn.mozillademos.org/files/12676/star.svg")) attr(img, "src", img_src_value);
		},
		m(target, anchor) {
			insert_experimental(target, div, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;