/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach,
	detach_all,
	init,
	insert,
	insert_all,
	make_renderer,
	noop,
	safe_not_equal,
	traverse
} from "svelte/internal";

const render_4 = make_renderer(`<p>a</p>`);

// (10:1) {#if a}
function create_if_block_4(ctx) {
	let render_nodes = [];

	return {
		c() {
			traverse(render_4(), render_nodes);
		},
		m(target, anchor) {
			insert(target, render_nodes[0], anchor); /* p */
		},
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* p */
		}
	};
}

const render_3 = make_renderer(`<p>b</p>`);

// (16:1) {#if b}
function create_if_block_3(ctx) {
	let render_nodes = [];

	return {
		c() {
			traverse(render_3(), render_nodes);
		},
		m(target, anchor) {
			insert(target, render_nodes[0], anchor); /* p */
		},
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* p */
		}
	};
}

const render_2 = make_renderer(`<p>c</p>`);

// (20:1) {#if c}
function create_if_block_2(ctx) {
	let render_nodes = [];

	return {
		c() {
			traverse(render_2(), render_nodes);
		},
		m(target, anchor) {
			insert(target, render_nodes[0], anchor); /* p */
		},
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* p */
		}
	};
}

const render_1 = make_renderer(`<p>d</p>`);

// (26:1) {#if d}
function create_if_block_1(ctx) {
	let render_nodes = [];

	return {
		c() {
			traverse(render_1(), render_nodes);
		},
		m(target, anchor) {
			insert(target, render_nodes[0], anchor); /* p */
		},
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* p */
		}
	};
}

const render = make_renderer(`<p>e</p>`);

// (33:0) {#if e}
function create_if_block(ctx) {
	let render_nodes = [];

	return {
		c() {
			traverse(render(), render_nodes);
		},
		m(target, anchor) {
			insert(target, render_nodes[0], anchor); /* p */
		},
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* p */
		}
	};
}

const render_5 = make_renderer(`<div><!> <p>this can be used as an anchor</p> <!> <!> <p>so can this</p> <!></div> <!>`);
const node_path_5 = () => [,0,1,-1,-1,1,1,1,1,-1,-1,1,2,1];

function create_fragment(ctx) {
	let render_nodes = [];
	let if_block0 = /*a*/ ctx[0] && create_if_block_4(ctx);
	let if_block1 = /*b*/ ctx[1] && create_if_block_3(ctx);
	let if_block2 = /*c*/ ctx[2] && create_if_block_2(ctx);
	let if_block3 = /*d*/ ctx[3] && create_if_block_1(ctx);
	let if_block4 = /*e*/ ctx[4] && create_if_block(ctx);

	return {
		c() {
			traverse(render_5(), render_nodes, node_path_5());
			if (if_block0) if_block0.c();
			if (if_block1) if_block1.c();
			if (if_block2) if_block2.c();
			if (if_block3) if_block3.c();
			if (if_block4) if_block4.c();
		},
		m(target, anchor) {
			insert_all(target, render_nodes, [0,12,13], anchor);
			if (if_block0) if_block0.m(render_nodes[0], render_nodes[1]);
			if (if_block1) if_block1.m(render_nodes[0], render_nodes[5]);
			if (if_block2) if_block2.m(render_nodes[0], render_nodes[7]);
			if (if_block3) if_block3.m(render_nodes[0], render_nodes[11]);
			if (if_block4) if_block4.m(target, render_nodes[13]);
		},
		p(ctx, [dirty]) {
			if (/*a*/ ctx[0]) {
				if (if_block0) {
					
				} else {
					if_block0 = create_if_block_4(ctx);
					if_block0.c();
					if_block0.m(render_nodes[0], render_nodes[1]);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (/*b*/ ctx[1]) {
				if (if_block1) {
					
				} else {
					if_block1 = create_if_block_3(ctx);
					if_block1.c();
					if_block1.m(render_nodes[0], render_nodes[5]);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			if (/*c*/ ctx[2]) {
				if (if_block2) {
					
				} else {
					if_block2 = create_if_block_2(ctx);
					if_block2.c();
					if_block2.m(render_nodes[0], render_nodes[7]);
				}
			} else if (if_block2) {
				if_block2.d(1);
				if_block2 = null;
			}

			if (/*d*/ ctx[3]) {
				if (if_block3) {
					
				} else {
					if_block3 = create_if_block_1(ctx);
					if_block3.c();
					if_block3.m(render_nodes[0], render_nodes[11]);
				}
			} else if (if_block3) {
				if_block3.d(1);
				if_block3 = null;
			}

			if (/*e*/ ctx[4]) {
				if (if_block4) {
					
				} else {
					if_block4 = create_if_block(ctx);
					if_block4.c();
					if_block4.m(render_nodes[13].parentNode, render_nodes[13]);
				}
			} else if (if_block4) {
				if_block4.d(1);
				if_block4 = null;
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			detach_all(detaching, render_nodes, [0,12,13]);
			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			if (if_block2) if_block2.d();
			if (if_block3) if_block3.d();
			if (if_block4) if_block4.d(detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { a } = $$props;
	let { b } = $$props;
	let { c } = $$props;
	let { d } = $$props;
	let { e } = $$props;

	$$self.$$set = $$props => {
		if ('a' in $$props) $$invalidate(0, a = $$props.a);
		if ('b' in $$props) $$invalidate(1, b = $$props.b);
		if ('c' in $$props) $$invalidate(2, c = $$props.c);
		if ('d' in $$props) $$invalidate(3, d = $$props.d);
		if ('e' in $$props) $$invalidate(4, e = $$props.e);
	};

	return [a, b, c, d, e];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { a: 0, b: 1, c: 2, d: 3, e: 4 });
	}
}

export default Component;