/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach,
	first_child,
	init,
	insert,
	make_renderer,
	next_sibling,
	noop,
	safe_not_equal
} from "svelte/internal";

const render_4 = make_renderer(`<p>a</p>`);

// (10:1) {#if a}
function create_if_block_4(ctx) {
	let p;

	return {
		c() {
			p = first_child(render_4());
		},
		m(target, anchor) {
			insert(target, p, anchor);
		},
		d(detaching) {
			if (detaching) detach(p);
		}
	};
}

const render_3 = make_renderer(`<p>b</p>`);

// (16:1) {#if b}
function create_if_block_3(ctx) {
	let p;

	return {
		c() {
			p = first_child(render_3());
		},
		m(target, anchor) {
			insert(target, p, anchor);
		},
		d(detaching) {
			if (detaching) detach(p);
		}
	};
}

const render_2 = make_renderer(`<p>c</p>`);

// (20:1) {#if c}
function create_if_block_2(ctx) {
	let p;

	return {
		c() {
			p = first_child(render_2());
		},
		m(target, anchor) {
			insert(target, p, anchor);
		},
		d(detaching) {
			if (detaching) detach(p);
		}
	};
}

const render_1 = make_renderer(`<p>d</p>`);

// (26:1) {#if d}
function create_if_block_1(ctx) {
	let p;

	return {
		c() {
			p = first_child(render_1());
		},
		m(target, anchor) {
			insert(target, p, anchor);
		},
		d(detaching) {
			if (detaching) detach(p);
		}
	};
}

const render = make_renderer(`<p>e</p>`);

// (33:0) {#if e}
function create_if_block(ctx) {
	let p;

	return {
		c() {
			p = first_child(render());
		},
		m(target, anchor) {
			insert(target, p, anchor);
		},
		d(detaching) {
			if (detaching) detach(p);
		}
	};
}

const render_5 = make_renderer(`<div><!> <p>this can be used as an anchor</p> <!> <!> <p>so can this</p> <!></div> <!>`);

function create_fragment(ctx) {
	let div;
	let if_block0_anchor;
	let t0;
	let p0;
	let t2;
	let if_block1_anchor;
	let t3;
	let if_block2_anchor;
	let t4;
	let p1;
	let t6;
	let if_block3_anchor;
	let t7;
	let if_block4_anchor;
	let if_block0 = /*a*/ ctx[0] && create_if_block_4(ctx);
	let if_block1 = /*b*/ ctx[1] && create_if_block_3(ctx);
	let if_block2 = /*c*/ ctx[2] && create_if_block_2(ctx);
	let if_block3 = /*d*/ ctx[3] && create_if_block_1(ctx);
	let if_block4 = /*e*/ ctx[4] && create_if_block(ctx);

	return {
		c() {
			div = first_child(render_5());
			if_block0_anchor = first_child(div);
			if (if_block0) if_block0.c();
			t0 = next_sibling(if_block0_anchor);
			p0 = next_sibling(t0);
			t2 = next_sibling(p0);
			if_block1_anchor = next_sibling(t2);
			if (if_block1) if_block1.c();
			t3 = next_sibling(if_block1_anchor);
			if_block2_anchor = next_sibling(t3);
			if (if_block2) if_block2.c();
			t4 = next_sibling(if_block2_anchor);
			p1 = next_sibling(t4);
			t6 = next_sibling(p1);
			if_block3_anchor = next_sibling(t6);
			if (if_block3) if_block3.c();
			t7 = next_sibling(div);
			if_block4_anchor = next_sibling(t7);
			if (if_block4) if_block4.c();
		},
		m(target, anchor) {
			insert(target, div, anchor);
			if (if_block0) if_block0.m(div, t0);
			if (if_block1) if_block1.m(div, t3);
			if (if_block2) if_block2.m(div, t4);
			if (if_block3) if_block3.m(div, null);
			insert(target, t7, anchor);
			if (if_block4) if_block4.m(target, anchor);
			insert(target, if_block4_anchor, anchor);
		},
		p(ctx, [dirty]) {
			if (/*a*/ ctx[0]) {
				if (if_block0) {
					
				} else {
					if_block0 = create_if_block_4(ctx);
					if_block0.c();
					if_block0.m(div, t0);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (/*b*/ ctx[1]) {
				if (if_block1) {
					
				} else {
					if_block1 = create_if_block_3(ctx);
					if_block1.c();
					if_block1.m(div, t3);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			if (/*c*/ ctx[2]) {
				if (if_block2) {
					
				} else {
					if_block2 = create_if_block_2(ctx);
					if_block2.c();
					if_block2.m(div, t4);
				}
			} else if (if_block2) {
				if_block2.d(1);
				if_block2 = null;
			}

			if (/*d*/ ctx[3]) {
				if (if_block3) {
					
				} else {
					if_block3 = create_if_block_1(ctx);
					if_block3.c();
					if_block3.m(div, null);
				}
			} else if (if_block3) {
				if_block3.d(1);
				if_block3 = null;
			}

			if (/*e*/ ctx[4]) {
				if (if_block4) {
					
				} else {
					if_block4 = create_if_block(ctx);
					if_block4.c();
					if_block4.m(if_block4_anchor.parentNode, if_block4_anchor);
				}
			} else if (if_block4) {
				if_block4.d(1);
				if_block4 = null;
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div);
			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			if (if_block2) if_block2.d();
			if (if_block3) if_block3.d();
			if (detaching) detach(t7);
			if (detaching) detach(if_block4_anchor);
			if (if_block4) if_block4.d(detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { a } = $$props;
	let { b } = $$props;
	let { c } = $$props;
	let { d } = $$props;
	let { e } = $$props;

	$$self.$$set = $$props => {
		if ('a' in $$props) $$invalidate(0, a = $$props.a);
		if ('b' in $$props) $$invalidate(1, b = $$props.b);
		if ('c' in $$props) $$invalidate(2, c = $$props.c);
		if ('d' in $$props) $$invalidate(3, d = $$props.d);
		if ('e' in $$props) $$invalidate(4, e = $$props.e);
	};

	return [a, b, c, d, e];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { a: 0, b: 1, c: 2, d: 3, e: 4 });
	}
}

export default Component;