/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	append,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space
} from "svelte/internal";

function create_fragment(ctx) {
	let section;
	let div;
	let h1;
	let t3;
	let p;

	return {
		c() {
			section = element("section");
			div = element("div");
			h1 = element("h1");
			h1.textContent = `Hello ${name}!`;
			t3 = space();
			p = element("p");
			p.textContent = `${description}`;
		},
		m(target, anchor) {
			insert(target, section, anchor);
			append(section, div);
			append(div, h1);
			append(div, t3);
			append(div, p);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(section);
		}
	};
}

let name = "world";
let description = "see below";

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;
