/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	attr,
	detach,
	init,
	insert,
	make_renderer,
	noop,
	safe_not_equal,
	traverse
} from "svelte/internal";

const render = make_renderer(`<div></div> <div></div>`);
const node_path = () => [,-1,-1];

function create_fragment(ctx) {
	let render_nodes = [];
	let div1_style_value;

	return {
		c() {
			traverse(render(), render_nodes, node_path());
			attr(render_nodes[0], "style", /*style*/ ctx[0]);
			attr(render_nodes[2], "style", div1_style_value = "" + (/*key*/ ctx[1] + ": " + /*value*/ ctx[2]));
		},
		m(target, anchor) {
			insert(target, render_nodes[0], anchor); /* div0 */
			insert(target, render_nodes[1], anchor); /* t */
			insert(target, render_nodes[2], anchor); /* div1 */
		},
		p(ctx, [dirty]) {
			if (dirty & /*style*/ 1) {
				attr(render_nodes[0], "style", /*style*/ ctx[0]);
			}

			if (dirty & /*key, value*/ 6 && div1_style_value !== (div1_style_value = "" + (/*key*/ ctx[1] + ": " + /*value*/ ctx[2]))) {
				attr(render_nodes[2], "style", div1_style_value);
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* div0 */
			if (detaching) detach(render_nodes[1]); /* t */
			if (detaching) detach(render_nodes[2]); /* div1 */
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { style } = $$props;
	let { key } = $$props;
	let { value } = $$props;

	$$self.$$set = $$props => {
		if ('style' in $$props) $$invalidate(0, style = $$props.style);
		if ('key' in $$props) $$invalidate(1, key = $$props.key);
		if ('value' in $$props) $$invalidate(2, value = $$props.value);
	};

	return [style, key, value];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { style: 0, key: 1, value: 2 });
	}
}

export default Component;