/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	append_styles,
	detach,
	init,
	insert,
	make_renderer,
	noop,
	safe_not_equal,
	set_data,
	traverse
} from "svelte/internal";

function add_css(target) {
	append_styles(target, "svelte-1a7i8ec", "p.svelte-1a7i8ec{color:red}");
}

const render = make_renderer(`<p class="svelte-1a7i8ec"> </p>`);
const node_path = () => [,0];

function create_fragment(ctx) {
	let render_nodes = [];

	return {
		c() {
			traverse(render(), render_nodes, node_path());
			render_nodes[1].data = /*foo*/ ctx[0];
		},
		m(target, anchor) {
			insert(target, render_nodes[0], anchor); /* p */
		},
		p(ctx, [dirty]) {
			if (dirty & /*foo*/ 1) set_data(render_nodes[1], /*foo*/ ctx[0]);
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* p */
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { foo = 42 } = $$props;

	$$self.$$set = $$props => {
		if ('foo' in $$props) $$invalidate(0, foo = $$props.foo);
	};

	return [foo];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { foo: 0 }, add_css);
	}
}

export default Component;