/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach,
	init,
	insert_experimental,
	listen,
	make_renderer,
	noop,
	prevent_default,
	run_all,
	safe_not_equal,
	stop_propagation
} from "svelte/internal";

const render = make_renderer(`<div><div>touch me</div> <button>click me</button> <button>or me</button> <button>or me!</button></div>`);

function create_fragment(ctx) {
	let div1;
	let div0;
	let button0;
	let button1;
	let button2;
	let mounted;
	let dispose;

	return {
		c() {
			div1 = render().firstChild;
			div0 = div1.firstElementChild;
			button0 = div0.nextElementSibling;
			button1 = button0.nextElementSibling;
			button2 = button1.nextElementSibling;
		},
		m(target, anchor) {
			insert_experimental(target, div1, anchor);

			if (!mounted) {
				dispose = [
					listen(div0, "touchstart", handleTouchstart, { passive: false }),
					listen(button0, "click", stop_propagation(prevent_default(handleClick))),
					listen(button1, "click", handleClick, { once: true, capture: true }),
					listen(button2, "click", handleClick, true),
					listen(div1, "touchstart", handleTouchstart, { passive: true })
				];

				mounted = true;
			}
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div1);
			mounted = false;
			run_all(dispose);
		}
	};
}

function handleTouchstart() {
	
} // ...

function handleClick() {
	
} // ...

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;