/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	claim_component,
	create_component,
	destroy_component,
	init,
	make_renderer,
	mount_component,
	safe_not_equal,
	transition_in,
	transition_out,
	trim_nodes
} from "svelte/internal";

import Layout from './Layout.svelte';
import Component from './Component.svelte';
const render = make_renderer(`<!>`);

// (6:0) <Layout>
function create_default_slot(ctx) {
	let component;
	let current;
	let cloned;
	component = new Component({});

	return {
		c() {
			create_component(component.$$.fragment);
			cloned = true;
		},
		l(nodes) {
			if (!cloned) this.c();
			if (nodes.length === 0) return;
			claim_component(component.$$.fragment, trim_nodes(nodes));
		},
		m(target, anchor) {
			mount_component(component, target, anchor);
			current = true;
		},
		i(local) {
			if (current) return;
			transition_in(component.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(component.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(component, detaching);
		}
	};
}

const render_1 = make_renderer(`<!>`);

function create_fragment(ctx) {
	let layout;
	let current;
	let cloned;

	layout = new Layout({
			props: {
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			}
		});

	return {
		c() {
			create_component(layout.$$.fragment);
			cloned = true;
		},
		l(nodes) {
			if (!cloned) this.c();
			if (nodes.length === 0) return;
			claim_component(layout.$$.fragment, trim_nodes(nodes));
		},
		m(target, anchor) {
			mount_component(layout, target, anchor);
			current = true;
		},
		p(ctx, [dirty]) {
			const layout_changes = {};

			if (dirty & /*$$scope*/ 1) {
				layout_changes.$$scope = { dirty, ctx };
			}

			layout.$set(layout_changes);
		},
		i(local) {
			if (current) return;
			transition_in(layout.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(layout.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(layout, detaching);
		}
	};
}

class Component_1 extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component_1;