/* generated by Svelte vX.Y.Z */
import {
	HtmlTagExperimental,
	SvelteComponent,
	destroy_each,
	detach,
	first_child,
	first_element_child,
	init,
	insert_experimental,
	make_renderer,
	next_element_sibling,
	next_sibling,
	noop,
	replace_blank,
	replace_text,
	safe_not_equal,
	set_data
} from "svelte/internal";

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[4] = list[i];
	child_ctx[6] = i;
	return child_ctx;
}

const render = make_renderer(`<div class="comment"><strong><!></strong> <span class="meta"><!> wrote <!> ago:</span> <!></div>`);

// (8:0) {#each comments as comment, i}
function create_each_block(ctx) {
	let div;
	let strong;
	let t0;
	let span;
	let t2_value = /*comment*/ ctx[4].author + "";
	let t2;
	let t3;
	let t4_value = /*elapsed*/ ctx[1](/*comment*/ ctx[4].time, /*time*/ ctx[2]) + "";
	let t4;
	let t6;
	let html_tag;
	let raw_value = /*comment*/ ctx[4].html + "";
	let html_anchor;

	return {
		c() {
			div = first_child(render());
			strong = first_element_child(div);
			t0 = replace_text(first_child(strong), /*i*/ ctx[6]);
			span = next_element_sibling(strong);
			t2 = replace_text(first_child(span), t2_value);
			t3 = next_sibling(t2);
			t4 = replace_text(next_sibling(t3), t4_value);
			t6 = next_sibling(span);
			html_tag = new HtmlTagExperimental();
			html_anchor = replace_blank(next_sibling(t6));
			html_tag.a = null;
		},
		m(target, anchor) {
			insert_experimental(target, div, anchor);
			html_tag.m(raw_value, div, null);
		},
		p(ctx, dirty) {
			if (dirty & /*comments*/ 1 && t2_value !== (t2_value = /*comment*/ ctx[4].author + "")) set_data(t2, t2_value);
			if (dirty & /*elapsed, comments, time*/ 7 && t4_value !== (t4_value = /*elapsed*/ ctx[1](/*comment*/ ctx[4].time, /*time*/ ctx[2]) + "")) set_data(t4, t4_value);
			if (dirty & /*comments*/ 1 && raw_value !== (raw_value = /*comment*/ ctx[4].html + "")) html_tag.p(raw_value);
		},
		d(detaching) {
			if (detaching) detach(div);
		}
	};
}

const render_1 = make_renderer(`<!> <p><!></p>`);

function create_fragment(ctx) {
	let each_1_anchor;
	let t0;
	let p;
	let t1;
	let each_value = /*comments*/ ctx[0];
	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	return {
		c() {
			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			each_1_anchor = replace_blank(first_child(render_1()));
			t0 = next_sibling(each_1_anchor);
			p = next_element_sibling(t0);
			t1 = replace_text(first_child(p), /*foo*/ ctx[3]);
		},
		m(target, anchor) {
			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(target, anchor);
			}

			insert_experimental(target, t0, anchor);
			insert_experimental(target, p, anchor);
		},
		p(ctx, [dirty]) {
			if (dirty & /*comments, elapsed, time*/ 7) {
				each_value = /*comments*/ ctx[0];
				let i;

				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(t0.parentNode, t0);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}

				each_blocks.length = each_value.length;
			}

			if (dirty & /*foo*/ 8) set_data(t1, /*foo*/ ctx[3]);
		},
		i: noop,
		o: noop,
		d(detaching) {
			destroy_each(each_blocks, detaching);
			if (detaching) detach(t0);
			if (detaching) detach(p);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { comments } = $$props;
	let { elapsed } = $$props;
	let { time } = $$props;
	let { foo } = $$props;

	$$self.$$set = $$props => {
		if ('comments' in $$props) $$invalidate(0, comments = $$props.comments);
		if ('elapsed' in $$props) $$invalidate(1, elapsed = $$props.elapsed);
		if ('time' in $$props) $$invalidate(2, time = $$props.time);
		if ('foo' in $$props) $$invalidate(3, foo = $$props.foo);
	};

	return [comments, elapsed, time, foo];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { comments: 0, elapsed: 1, time: 2, foo: 3 });
	}
}

export default Component;