/* generated by Svelte vX.Y.Z */
import {
	HtmlTag,
	SvelteComponent,
	destroy_each,
	detach,
	detach_all,
	init,
	insert,
	insert_all,
	make_renderer,
	noop,
	replace_text,
	safe_not_equal,
	set_data,
	traverse
} from "svelte/internal";

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[4] = list[i];
	child_ctx[6] = i;
	return child_ctx;
}

const render = make_renderer(`<div class="comment"><strong> </strong> <span class="meta"><!> wrote <!> ago:</span> <!></div>`);
const node_path = () => [,,0,-3,-1,0,-1,1,-1,-6,1];

// (8:0) {#each comments as comment, i}
function create_each_block(ctx) {
	let render_nodes = [];
	let t2_value = /*comment*/ ctx[4].author + "";
	let t4_value = /*elapsed*/ ctx[1](/*comment*/ ctx[4].time, /*time*/ ctx[2]) + "";
	let html_tag;
	let raw_value = /*comment*/ ctx[4].html + "";

	return {
		c() {
			traverse(render(), render_nodes, node_path());
			render_nodes[2].data = /*i*/ ctx[6];
			render_nodes[5] = replace_text(render_nodes[5], t2_value);
			render_nodes[7] = replace_text(render_nodes[7], t4_value);
			html_tag = new HtmlTag(false);
			html_tag.a = render_nodes[10];
		},
		m(target, anchor) {
			insert(target, render_nodes[0], anchor); /* div */
			html_tag.m(raw_value, render_nodes[0], render_nodes[10]);
		},
		p(ctx, dirty) {
			if (dirty & /*comments*/ 1 && t2_value !== (t2_value = /*comment*/ ctx[4].author + "")) set_data(render_nodes[5], t2_value);
			if (dirty & /*elapsed, comments, time*/ 7 && t4_value !== (t4_value = /*elapsed*/ ctx[1](/*comment*/ ctx[4].time, /*time*/ ctx[2]) + "")) set_data(render_nodes[7], t4_value);
			if (dirty & /*comments*/ 1 && raw_value !== (raw_value = /*comment*/ ctx[4].html + "")) html_tag.p(raw_value);
		},
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* div */
		}
	};
}

const render_1 = make_renderer(`<!> <p> </p>`);
const node_path_1 = () => [0,1,1,0];

function create_fragment(ctx) {
	let render_nodes = [];
	let each_value = /*comments*/ ctx[0];
	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	return {
		c() {
			traverse(render_1(), render_nodes, node_path_1());

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			render_nodes[3].data = /*foo*/ ctx[3];
		},
		m(target, anchor) {
			insert_all(target, render_nodes, [0,1,2], anchor);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(target, render_nodes[0]);
			}
		},
		p(ctx, [dirty]) {
			if (dirty & /*comments, elapsed, time*/ 7) {
				each_value = /*comments*/ ctx[0];
				let i;

				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(render_nodes[0].parentNode, render_nodes[0]);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}

				each_blocks.length = each_value.length;
			}

			if (dirty & /*foo*/ 8) set_data(render_nodes[3], /*foo*/ ctx[3]);
		},
		i: noop,
		o: noop,
		d(detaching) {
			detach_all(detaching, render_nodes, [0,1,2]);
			destroy_each(each_blocks, detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { comments } = $$props;
	let { elapsed } = $$props;
	let { time } = $$props;
	let { foo } = $$props;

	$$self.$$set = $$props => {
		if ('comments' in $$props) $$invalidate(0, comments = $$props.comments);
		if ('elapsed' in $$props) $$invalidate(1, elapsed = $$props.elapsed);
		if ('time' in $$props) $$invalidate(2, time = $$props.time);
		if ('foo' in $$props) $$invalidate(3, foo = $$props.foo);
	};

	return [comments, elapsed, time, foo];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { comments: 0, elapsed: 1, time: 2, foo: 3 });
	}
}

export default Component;
