/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	action_destroyer,
	detach,
	init,
	insert,
	is_function,
	make_renderer,
	noop,
	safe_not_equal,
	traverse
} from "svelte/internal";

const render = make_renderer(`<button>foo</button>`);

function create_fragment(ctx) {
	let render_nodes = [];
	let foo_action;
	let mounted;
	let dispose;

	return {
		c() {
			traverse(render(), render_nodes);
		},
		m(target, anchor) {
			insert(target, render_nodes[0], anchor); /* button */

			if (!mounted) {
				dispose = action_destroyer(foo_action = foo.call(null, render_nodes[0], /*foo_function*/ ctx[1]));
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (foo_action && is_function(foo_action.update) && dirty & /*bar*/ 1) foo_action.update.call(null, /*foo_function*/ ctx[1]);
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* button */
			mounted = false;
			dispose();
		}
	};
}

function handleFoo(bar) {
	console.log(bar);
}

function foo(node, callback) {
	
} // code goes here

function instance($$self, $$props, $$invalidate) {
	let { bar } = $$props;
	const foo_function = () => handleFoo(bar);

	$$self.$$set = $$props => {
		if ('bar' in $$props) $$invalidate(0, bar = $$props.bar);
	};

	return [bar, foo_function];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { bar: 0 });
	}
}

export default Component;