/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach,
	init,
	insert_hydration,
	make_renderer,
	noop,
	safe_not_equal,
	traverse,
	traverse_claim
} from "svelte/internal";

const render = make_renderer(`<svg><title>a title</title></svg>`);
const node_path = () => [0];

function create_fragment(ctx) {
	let render_nodes = [];

	return {
		c() {
			traverse(render(), render_nodes);
		},
		l(nodes) {
			this.c();
			if (!nodes.length) return;
			traverse_claim(nodes, render_nodes, [0]);
		},
		m(target, anchor) {
			insert_hydration(target, render_nodes[0], anchor); /* svg */
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* svg */
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;