/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	children,
	claim_element,
	claim_text,
	detach,
	first_child,
	init,
	insert_hydration,
	make_renderer,
	noop,
	safe_not_equal,
	trim_nodes
} from "svelte/internal";

const render = make_renderer(`<svg><title>a title</title></svg>`);

function create_fragment(ctx) {
	let svg;
	let title;
	let t;

	return {
		c() {
			svg = first_child(render());
			title = first_child(svg);
			t = first_child(title);
		},
		l(nodes) {
			this.c();
			if (!nodes.length) return;
			svg = claim_element(svg, nodes);
			var svg_nodes = children(svg);
			title = claim_element(title, svg_nodes, svg);
			t = claim_text(t, trim_nodes(children(title)), title);
		},
		m(target, anchor) {
			insert_hydration(target, svg, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(svg);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;