/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach,
	first_child,
	first_element_child,
	init,
	insert_experimental,
	make_renderer,
	noop,
	safe_not_equal
} from "svelte/internal";

const render = make_renderer(`<template><div>foo</div></template>`);

function create_fragment(ctx) {
	let template;
	let div;

	return {
		c() {
			template = first_child(render());
			div = first_element_child(template.content);
		},
		m(target, anchor) {
			insert_experimental(target, template, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(template);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;