/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	append_hydration,
	claim_template_element,
	detach,
	first_child,
	init,
	insert_hydration,
	make_renderer,
	next_element_sibling,
	noop,
	query_selector_all,
	safe_not_equal
} from "svelte/internal";

const render_1 = make_renderer(`<link rel="canonical" href="/"><meta name="description" content="some description"><meta name="keywords" content="some keywords">`);
const render = make_renderer(`<div>Just a dummy page.</div>`);

function create_fragment(ctx) {
	let link;
	let meta0;
	let meta1;
	let div;
	let cloned;

	return {
		c() {
			link = first_child(render_1());
			meta0 = next_element_sibling(link);
			meta1 = next_element_sibling(meta0);
			div = first_child(render());
			cloned = true;
			this.h();
		},
		l(nodes) {
			if (!cloned) this.c();
			const head_nodes = query_selector_all('[data-svelte=\"svelte-1s8aodm\"]', document.head);
			link = claim_template_element(link, head_nodes, document.head);
			meta0 = claim_template_element(meta0, head_nodes, document.head);
			meta1 = claim_template_element(meta1, head_nodes, document.head);
			head_nodes.forEach(detach);
			if (nodes.length === 0) return;
			div = claim_template_element(div, nodes);
			this.h();
		},
		h() {
			document.title = "Some Title";
		},
		m(target, anchor) {
			append_hydration(document.head, link);
			append_hydration(document.head, meta0);
			append_hydration(document.head, meta1);
			insert_hydration(target, div, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			detach(link);
			detach(meta0);
			detach(meta1);
			if (detaching) detach(div);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;