/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach,
	first_child,
	init,
	insert_experimental,
	make_renderer,
	next_sibling,
	noop,
	replace_text,
	safe_not_equal
} from "svelte/internal";

const render = make_renderer(`<!> <!>`);

function create_fragment(ctx) {
	let t0;
	let t1;
	let t2_value = import.meta.url + "";
	let t2;

	return {
		c() {
			t0 = replace_text(first_child(render()), /*url*/ ctx[0]);
			t1 = next_sibling(t0);
			t2 = replace_text(next_sibling(t1), t2_value);
		},
		m(target, anchor) {
			insert_experimental(target, t0, anchor);
			insert_experimental(target, t1, anchor);
			insert_experimental(target, t2, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(t0);
			if (detaching) detach(t1);
			if (detaching) detach(t2);
		}
	};
}

function instance($$self) {
	const url = import.meta.url;
	return [url];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Component;