/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach,
	init,
	insert,
	make_renderer,
	noop,
	replace_text,
	safe_not_equal,
	traverse
} from "svelte/internal";

const render = make_renderer(`<!> <!>`);
const node_path = () => [0,1,2];

function create_fragment(ctx) {
	let render_nodes = [];
	let t2_value = import.meta.url + "";

	return {
		c() {
			traverse(render(), render_nodes, node_path());
			render_nodes[0] = replace_text(render_nodes[0], /*url*/ ctx[0]);
			render_nodes[2] = replace_text(render_nodes[2], t2_value);
		},
		m(target, anchor) {
			insert(target, render_nodes[0], anchor); /* t0 */
			insert(target, render_nodes[1], anchor); /* t1 */
			insert(target, render_nodes[2], anchor); /* t2 */
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(render_nodes[0]); /* t0 */
			if (detaching) detach(render_nodes[1]); /* t1 */
			if (detaching) detach(render_nodes[2]); /* t2 */
		}
	};
}

function instance($$self) {
	const url = import.meta.url;
	return [url];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Component;