/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach_all,
	init,
	insert_all,
	listen,
	make_renderer,
	noop,
	run_all,
	safe_not_equal,
	traverse
} from "svelte/internal";

const render = make_renderer(`<input type="file"> <input type="file">`);
const node_path = () => [,1,1];

function create_fragment(ctx) {
	let render_nodes = [];
	let mounted;
	let dispose;

	return {
		c() {
			traverse(render(), render_nodes, node_path());
		},
		m(target, anchor) {
			insert_all(target, render_nodes, [0,1,2], anchor);

			if (!mounted) {
				dispose = [
					listen(render_nodes[0], "change", /*input0_change_handler*/ ctx[1]),
					listen(render_nodes[2], "change", /*input1_change_handler*/ ctx[2])
				];

				mounted = true;
			}
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			detach_all(detaching, render_nodes, [0,1,2]);
			mounted = false;
			run_all(dispose);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { files } = $$props;

	function input0_change_handler() {
		files = this.files;
		$$invalidate(0, files);
	}

	function input1_change_handler() {
		files = this.files;
		$$invalidate(0, files);
	}

	$$self.$$set = $$props => {
		if ('files' in $$props) $$invalidate(0, files = $$props.files);
	};

	return [files, input0_change_handler, input1_change_handler];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { files: 0 });
	}
}

export default Component;