/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	component_subscribe,
	detach,
	first_child,
	init,
	insert_experimental,
	make_renderer,
	next_element_sibling,
	next_sibling,
	noop,
	safe_not_equal,
	subscribe,
	toggle_class
} from "svelte/internal";

import { reactiveStoreVal, unreactiveExport } from './store';
const render = make_renderer(`<div></div> <div></div> <div></div> <div></div> <div></div> <div></div> <div></div> <div></div> <div></div>`);

function create_fragment(ctx) {
	let div0;
	let t0;
	let div1;
	let t1;
	let div2;
	let t2;
	let div3;
	let t3;
	let div4;
	let t4;
	let div5;
	let t5;
	let div6;
	let t6;
	let div7;
	let t7;
	let div8;

	return {
		c() {
			div0 = first_child(render());
			t0 = next_sibling(div0);
			div1 = next_element_sibling(t0);
			t1 = next_sibling(div1);
			div2 = next_element_sibling(t1);
			t2 = next_sibling(div2);
			div3 = next_element_sibling(t2);
			t3 = next_sibling(div3);
			div4 = next_element_sibling(t3);
			t4 = next_sibling(div4);
			div5 = next_element_sibling(t4);
			t5 = next_sibling(div5);
			div6 = next_element_sibling(t5);
			t6 = next_sibling(div6);
			div7 = next_element_sibling(t6);
			t7 = next_sibling(div7);
			div8 = next_element_sibling(t7);
			toggle_class(div0, "update1", reactiveModuleVar);
			toggle_class(div1, "update2", /*reactiveConst*/ ctx[0].x);
			toggle_class(div2, "update3", nonReactiveGlobal && /*reactiveConst*/ ctx[0].x);
			toggle_class(div3, "update4", /*$reactiveStoreVal*/ ctx[2]);
			toggle_class(div4, "update5", /*$reactiveDeclaration*/ ctx[3]);
			toggle_class(div5, "static1", nonReactiveModuleVar);
			toggle_class(div6, "static2", nonReactiveGlobal);
			toggle_class(div7, "static3", nonReactiveModuleVar && nonReactiveGlobal);
			toggle_class(div8, "static4", unreactiveExport);
		},
		m(target, anchor) {
			insert_experimental(target, div0, anchor);
			insert_experimental(target, t0, anchor);
			insert_experimental(target, div1, anchor);
			insert_experimental(target, t1, anchor);
			insert_experimental(target, div2, anchor);
			insert_experimental(target, t2, anchor);
			insert_experimental(target, div3, anchor);
			insert_experimental(target, t3, anchor);
			insert_experimental(target, div4, anchor);
			insert_experimental(target, t4, anchor);
			insert_experimental(target, div5, anchor);
			insert_experimental(target, t5, anchor);
			insert_experimental(target, div6, anchor);
			insert_experimental(target, t6, anchor);
			insert_experimental(target, div7, anchor);
			insert_experimental(target, t7, anchor);
			insert_experimental(target, div8, anchor);
		},
		p(ctx, [dirty]) {
			if (dirty & /*reactiveModuleVar*/ 0) {
				toggle_class(div0, "update1", reactiveModuleVar);
			}

			if (dirty & /*reactiveConst*/ 1) {
				toggle_class(div1, "update2", /*reactiveConst*/ ctx[0].x);
			}

			if (dirty & /*nonReactiveGlobal, reactiveConst*/ 1) {
				toggle_class(div2, "update3", nonReactiveGlobal && /*reactiveConst*/ ctx[0].x);
			}

			if (dirty & /*$reactiveStoreVal*/ 4) {
				toggle_class(div3, "update4", /*$reactiveStoreVal*/ ctx[2]);
			}

			if (dirty & /*$reactiveDeclaration*/ 8) {
				toggle_class(div4, "update5", /*$reactiveDeclaration*/ ctx[3]);
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div0);
			if (detaching) detach(t0);
			if (detaching) detach(div1);
			if (detaching) detach(t1);
			if (detaching) detach(div2);
			if (detaching) detach(t2);
			if (detaching) detach(div3);
			if (detaching) detach(t3);
			if (detaching) detach(div4);
			if (detaching) detach(t4);
			if (detaching) detach(div5);
			if (detaching) detach(t5);
			if (detaching) detach(div6);
			if (detaching) detach(t6);
			if (detaching) detach(div7);
			if (detaching) detach(t7);
			if (detaching) detach(div8);
		}
	};
}

let nonReactiveModuleVar = Math.random();
let reactiveModuleVar = Math.random();

function instance($$self, $$props, $$invalidate) {
	let reactiveDeclaration;
	let $reactiveStoreVal;

	let $reactiveDeclaration,
		$$unsubscribe_reactiveDeclaration = noop,
		$$subscribe_reactiveDeclaration = () => ($$unsubscribe_reactiveDeclaration(), $$unsubscribe_reactiveDeclaration = subscribe(reactiveDeclaration, $$value => $$invalidate(3, $reactiveDeclaration = $$value)), reactiveDeclaration);

	component_subscribe($$self, reactiveStoreVal, $$value => $$invalidate(2, $reactiveStoreVal = $$value));
	$$self.$$.on_destroy.push(() => $$unsubscribe_reactiveDeclaration());
	nonReactiveGlobal = Math.random();
	const reactiveConst = { x: Math.random() };
	reactiveModuleVar += 1;

	if (Math.random()) {
		reactiveConst.x += 1;
	}

	$: $$subscribe_reactiveDeclaration($$invalidate(1, reactiveDeclaration = reactiveModuleVar * 2));
	return [reactiveConst, reactiveDeclaration, $reactiveStoreVal, $reactiveDeclaration];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Component;