/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	component_subscribe,
	detach_all,
	init,
	insert_all,
	make_renderer,
	noop,
	safe_not_equal,
	subscribe,
	toggle_class,
	traverse
} from "svelte/internal";

import { reactiveStoreVal, unreactiveExport } from './store';
const render = make_renderer(`<div></div> <div></div> <div></div> <div></div> <div></div> <div></div> <div></div> <div></div> <div></div>`);
const node_path = () => [,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1];

function create_fragment(ctx) {
	let render_nodes = [];

	return {
		c() {
			traverse(render(), render_nodes, node_path());
			toggle_class(render_nodes[0], "update1", reactiveModuleVar);
			toggle_class(render_nodes[2], "update2", /*reactiveConst*/ ctx[0].x);
			toggle_class(render_nodes[4], "update3", nonReactiveGlobal && /*reactiveConst*/ ctx[0].x);
			toggle_class(render_nodes[6], "update4", /*$reactiveStoreVal*/ ctx[2]);
			toggle_class(render_nodes[8], "update5", /*$reactiveDeclaration*/ ctx[3]);
			toggle_class(render_nodes[10], "static1", nonReactiveModuleVar);
			toggle_class(render_nodes[12], "static2", nonReactiveGlobal);
			toggle_class(render_nodes[14], "static3", nonReactiveModuleVar && nonReactiveGlobal);
			toggle_class(render_nodes[16], "static4", unreactiveExport);
		},
		m(target, anchor) {
			insert_all(target, render_nodes, [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16], anchor);
		},
		p(ctx, [dirty]) {
			if (dirty & /*reactiveModuleVar*/ 0) {
				toggle_class(render_nodes[0], "update1", reactiveModuleVar);
			}

			if (dirty & /*reactiveConst*/ 1) {
				toggle_class(render_nodes[2], "update2", /*reactiveConst*/ ctx[0].x);
			}

			if (dirty & /*nonReactiveGlobal, reactiveConst*/ 1) {
				toggle_class(render_nodes[4], "update3", nonReactiveGlobal && /*reactiveConst*/ ctx[0].x);
			}

			if (dirty & /*$reactiveStoreVal*/ 4) {
				toggle_class(render_nodes[6], "update4", /*$reactiveStoreVal*/ ctx[2]);
			}

			if (dirty & /*$reactiveDeclaration*/ 8) {
				toggle_class(render_nodes[8], "update5", /*$reactiveDeclaration*/ ctx[3]);
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			detach_all(detaching, render_nodes, [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]);
		}
	};
}

let nonReactiveModuleVar = Math.random();
let reactiveModuleVar = Math.random();

function instance($$self, $$props, $$invalidate) {
	let reactiveDeclaration;
	let $reactiveStoreVal;

	let $reactiveDeclaration,
		$$unsubscribe_reactiveDeclaration = noop,
		$$subscribe_reactiveDeclaration = () => ($$unsubscribe_reactiveDeclaration(), $$unsubscribe_reactiveDeclaration = subscribe(reactiveDeclaration, $$value => $$invalidate(3, $reactiveDeclaration = $$value)), reactiveDeclaration);

	component_subscribe($$self, reactiveStoreVal, $$value => $$invalidate(2, $reactiveStoreVal = $$value));
	$$self.$$.on_destroy.push(() => $$unsubscribe_reactiveDeclaration());
	nonReactiveGlobal = Math.random();
	const reactiveConst = { x: Math.random() };
	reactiveModuleVar += 1;

	if (Math.random()) {
		reactiveConst.x += 1;
	}

	$: $$subscribe_reactiveDeclaration($$invalidate(1, reactiveDeclaration = reactiveModuleVar * 2));
	return [reactiveConst, reactiveDeclaration, $reactiveStoreVal, $reactiveDeclaration];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Component;